name: DocFX - Documentation Process
on:
  push:
    branches:
      - develop
jobs:
  document:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOCFX_SOURCE_BRANCH_NAME: ${{ github.ref }}
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
    steps:
      - name: Echo Log Information
        run: |
          echo "Trigger   : ${{ github.event_name }}"
          echo "OS        : ${{ runner.os }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch    : ${{ github.ref }}"
          echo "Job status: ${{ job.status }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run:  ls -R ${{ github.workspace }}
      - name: Get docfx
        run: |
          curl -L https://github.com/dotnet/docfx/releases/latest/download/docfx.zip -o docfx.zip
          unzip -d .docfx docfx.zip
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build docs
        run: |
          which dotnet
          ls "${{ github.workspace }}/docs/"
          cat "${{ github.workspace }}/docs/docfx.json"
          .docfx/docfx.exe metadata "${{ github.workspace }}/docs/docfx.json"
          .docfx/docfx.exe "${{ github.workspace }}/docs/docfx.json"
          ls "${{ github.workspace }}/docs"
