name: DocFX - Documentation Process
on:
  push:
    branches:
      - develop
jobs:
  document:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOCFX_SOURCE_BRANCH_NAME: ${{ github.ref }}
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
    steps:
      - name: Echo Log Information
        run: |
          echo "Trigger   : ${{ github.event_name }}"
          echo "OS        : ${{ runner.os }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch    : ${{ github.ref }}"
          echo "Job status: ${{ job.status }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run:  ls -R ${{ github.workspace }}
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Get DocFX & Build docs
        shell: pwsh
        run: |
          curl -L https://github.com/dotnet/docfx/releases/latest/download/docfx.zip -o ${{ github.workspace }}/docfx.zip
          unzip -d ${{ github.workspace }}/docfx ${{ github.workspace }}/docfx.zip
          chmod -R 777 ${{ github.workspace }}/docfx
          Write-Host "Docs:"
          Get-ChildItem "${{ github.workspace }}/docs/"
          | Select-Object -Property Name,FullName,Size,UnixMode
          | Format-Table
          | Out-String
          | Write-Host
          Write-Host "`ndocfx.json:"
          cat "${{ github.workspace }}/docs/docfx.json"
          Get-ChildItem
          | Select-Object -Property Name,FullName,Size,UnixMode
          | Format-Table
          | Out-String
          | Write-Host
          Get-ChildItem ./docfx
          | Select-Object -Property Name,FullName,Size,UnixMode
          | Format-Table
          | Out-String
          | Write-Host
          Write-Host "`nGenerating API documentation:"
          & ./docfx/docfx.exe metadata "${{ github.workspace }}/docs/docfx.json"
          Write-Host "`nCreating docfx site:"
          & ./docfx/docfx.exe "${{ github.workspace }}/docs/docfx.json"
          Write-Host "`nDocs:"
          Get-ChildItem "${{ github.workspace }}/docs/"
          | Select-Object -Property Name,FullName,Size,UnixMode
          | Format-Table
          | Out-String
          | Write-Host
