name: Build Cloud-ShareSync
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOCFX_SOURCE_BRANCH_NAME: ${{ github.ref }}

    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      - name: Echo Log Information
        run: |
          echo "Trigger   : ${{ github.event_name }}"
          echo "OS        : ${{ runner.os }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch    : ${{ github.ref }}"
          echo "Job status: ${{ job.status }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build Cloud-ShareSync
        shell: pwsh
        run: |
          $BuildScript = (Resolve-Path -Path ./build/BuildCloudShareSync.ps1).Path
          $Params = @{
            SOURCEPATH  = (Get-Location).Path
            PUBLISHPATH = Join-Path -Path "$env:GITHUB_WORKSPACE" -ChildPath 'Publish'
            Verbose     = $true
          }
          & $BuildScript @Params

          # Write out what was built.
          Get-ChildItem -Path $Params['PUBLISHPATH'] -recurse
          | Select-Object -Property Name,Size
          | Format-List
          | Write-Host
      - run: |
          echo "Job status: ${{ job.status }}"
