name: Publish PreRelease
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'PreRelease Tag'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: develop
    permissions:
      contents: read
      packages: write
    env:
      DOTNET_NOLOGO: true

    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build SimpleBackup
        shell: pwsh
        run: |
          $BuildScript = (Resolve-Path -Path ./build/BuildSimpleBackup.ps1).Path
          $Params = @{
            SOURCEPATH  = (Get-Location).Path
            PUBLISHPATH = Join-Path -Path "$env:GITHUB_WORKSPACE" -ChildPath 'Publish'
            Verbose     = $true
          }
          & $BuildScript @Params

      - name: Run Infer#
        uses: microsoft/infersharpaction@v1.2.1
        id: runinfersharp
        with:
          binary-path: "${{ github.workspace }}/Publish/Linux/"

      - name: Write Infer# output to artifact
        shell: pwsh
        run: |
          $InferPath = Join-Path -Path "$env:GITHUB_WORKSPACE" -ChildPath 'Publish' -AdditionalChildPath "InferReport.txt"
          Write-Output "${{ steps.runinfersharp.outputs.results }}"  | Tee-Object -FilePath $InferPath -Append

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: Linux_{{ github.sha }}
          path: ${{ github.workspace }}/Publish/Linux

      - name: Upload MacOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: MacOS_{{ github.sha }}
          path: ${{ github.workspace }}/Publish/MacOS

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows_{{ github.sha }}
          path: ${{ github.workspace }}/Publish/Windows

      - name: Upload InferReport artifact
        uses: actions/upload-artifact@v3
        with:
          name: InferReport_{{ github.sha }}
          path: ${{ github.workspace }}/Publish/InferReport.txt

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-sb
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha,format=long
            type=raw,value=simplebackup-${{ github.event.inputs.tags }}
            type=raw,value={{branch}}-{{date 'YYYYMMDD'}}

      - name: Build and push SimpleBackup Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          file: ./src/SimpleBackup/Dockerfile
          push: true
          tags: ${{ steps.meta-sb.outputs.tags }}
          labels: ${{ steps.meta-sb.outputs.labels }}
